### ISSUE TITLE
Python 3 and other versions

### ISSUE THREAD

**Issue by OleinikovasV** [mgalardini/pdb2uniprot#2]
Dear @mgalardini,

Big thanks for this script! I would like to use it for my PDB-wide queries to analyze related structures for their flexible features and given inconsistencies in the PDB this is immensely useful!
I was wondering if there are plans to adapt the code to python 3?
Also, are there plans to make it standalone or part of some other python library? If it could map the data to arrays or be part of an easily installable package, I believe, it would benefit a lot more users.

Best wishes,
Vladas

**Comment by mgalardini** [comment]
Hi,

thanks for your interest in this humble script; I just pushed a commit to make it compatible to python3. As for the other question, I am not planning to convert this into a module for the moment, but I'll be happy to spend some time on it if more people will make a good case for it.

Hope this helps,
M
