### ISSUE TITLE
How to link pdb2uniprot to xml?

### ISSUE THREAD

**Issue by xj7757417771** [mgalardini/pdb2uniprot#3]
Hello,

I used "curl --silent "ftp://ftp.ebi.ac.uk/pub/databases/msd/sifts/xml/1kf6.xml.gz" | gunzip | python parse_sifts.py"  to map PDB  to Uniprot. However, the program has not responded. I went to the "ftp://ftp.ebi.ac.uk/pub/databases/msd/sifts/xml/" directory and found that the directory could not be opened. Can you send me a copy of the file in this directory?
Thank you very much!

Sincerely,
Juan Xie

**Comment by mgalardini** [comment]
Hi,

sorry to hear you are encountering problems: I have just tried your command and it works as expected for me. Are you sure your internet connection is fine? Have you tried loading the xml URL in the browser?

Best,
Marco

**Comment by xj7757417771** [comment]
Hello,
Thank you for your reply. My network is normal, and I also let my classmates try to open "ftp://ftp.ebi.ac.uk/pub/databases/msd/sifts/xml/", but they can't open it either. If it is convenient, I hope that you can transfer the files under this page to me. My email address is "M201570116@hust.edu.cn". Thank you very much!
Sincerely,
Xie Juan

**Comment by mgalardini** [comment]
Oh, can it be that for some reason the EBI ftp is blocked from your institution? Have you tried with a VPN or from a different network? I'm afraid that the directory contains several thousand files, and it wouldn't be practical for me to send it over. Sorry about that...
